name: image builder

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gh-runner
      - name: Install incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x
      - name: Reset the firewall
        run: |
          sudo nft flush ruleset
      - name: Init incus
        run: |
          sudo incus admin init --auto
      - name: Add remte incus server
        run: |
          sudo incus remote add ${{ secrets.INCUS_NAME }} ${{ secrets.INCUS_SERVER }} --token=${{ secrets.INCUS_TOKEN }} --accept-certificate
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Packer init
        run: |
          sudo packer init .
      - name: Packer build
        run: |
          sudo packer build -on-error=abort debian.pkr.hcl