name: image builder

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install incus
        run: |
          curl https://pkgs.zabbly.com/get/incus-stable | sudo sh -x
      - name: Reset the firewall
        run: |
          sudo nft flush ruleset
      - name: Init incus
        run: |
          sudo incus admin init --auto
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Packer init
        run: |
          packer init .
      - name: Packer build
        run: |
          packer build -on-error=abort debian.pkr.hcl